### ISSUE TITLE
Detect the import of those packages and suggests alternative with ESLint

### ISSUE THREAD

**Issue by SukkaW** [43081j/ecosystem-cleanup#18]
I myself maintain such a list in my eslint configuration (to work with `no-restricted-require` and `no-restricted-import`):

https://github.com/SukkaW/eslint-config-sukka/blob/master/packages/shared/src/restricted-import.ts

The project could provide a preset (a simple JSON would do).

**Comment by 43081j** [comment]
that's a good idea!

i have some prior art here too that never really turned into anything useful:
https://github.com/43081j/eslint-plugin-clutter/blob/master/src/messages.ts

doing it via restricted imports is a much better idea.

i have some things to figure out around setting up an org for the results of this cleanup, but once that exists, we could host a simple preset there

**Comment by 43081j** [comment]
closing since we now have:
https://github.com/es-tooling/eslint-plugin-depend/
