### ISSUE TITLE
Migrate freecodecamp to npm-run-all2

### ISSUE THREAD

**Issue by 43081j** [43081j/ecosystem-cleanup#25]
freecodecamp uses npm-run-all here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/10a067308b4a4da2d0eb750cc08bc8c42f962d54/package.json#L25

we should move it to use npm-run-all2 (reduced size, security updates, etc):
https://github.com/bcomnes/npm-run-all2

**Comment by leefreemanxyz** [comment]
I think this has been completed in this PR by the Mend/Renovate bot https://github.com/freeCodeCamp/freeCodeCamp/pull/53416

**Comment by 43081j** [comment]
Looks good to me!

Closing this 🎉
