### ISSUE TITLE
migrate nextjs to npm-run-all2

### ISSUE THREAD

**Issue by 43081j** [43081j/ecosystem-cleanup#26]
the next monorepo uses npm-run-all:
https://github.com/vercel/next.js/blob/aa66300f7564e931c189bef3a6b96ee9caa44e3c/package.json#L182

we should move this to npm-run-all2 (lighter, more up to date):
https://github.com/bcomnes/npm-run-all2

**Comment by 43081j** [comment]
opened vercel/next.js#62610

**Comment by andriyor** [comment]
looks like they already migrated

**Comment by 43081j** [comment]
you're right! they removed it entirely in the end

closing 🥳
